feat(ns-ha): add reset function

diff --git a/packages/ns-ha/files/ns-ha-config b/packages/ns-ha/files/ns-ha-config
--- a/packages/ns-ha/files/ns-ha-config
+++ b/packages/ns-ha/files/ns-ha-config
@@ -24,6 +24,7 @@ help() {
   echo "  check-main-node"
   echo "  check-backup-node"
   echo "  show-config"
+  echo "  reset"
   echo "  status (This is the only action that can be run on the backup node)"
 }
 
@@ -313,6 +314,24 @@ remove_alias() {
   success
 }
 
+reset() {
+  read -p "Are you sure you want to reset the HA configuration? This action cannot be undone. (yes/no): " CONFIRMATION
+  if [[ "$CONFIRMATION" != "yes" ]]; then
+    echo "Reset operation canceled."
+    exit 0
+  fi
+  echo -n "Resetting HA configuration... "
+  OUTPUT=$(echo '{"role": "main"}' | /usr/libexec/rpcd/ns.ha call reset)
+
+  if [[ $? -ne 0 ]]; then
+    error
+    echo "Failed to reset the HA configuration."
+    exit 1
+  fi
+
+  success
+}
+
 status() {
   OUTPUT=$(/usr/libexec/rpcd/ns.ha call status)
   ROLE=$(echo "$OUTPUT" | jq -r '.role')
@@ -434,6 +453,9 @@ case "$ACTION" in
     ;;
   show-config)
     show_config
+    ;;
+  reset)
+    reset
     ;;
   status)
     status
