feat: added IPS (#1041)

diff --git a/packages/snort3/files/snort.init b/packages/snort3/files/snort.init
--- a/packages/snort3/files/snort.init
+++ b/packages/snort3/files/snort.init
@@ -17,34 +17,27 @@ validate_snort_section() {
 		'interface:string'
 }
 
-update_bypass_set() {
-	set_name=$1
-	set_file="/var/ns-snort/${set_name}.conf"
-	ips=$(uci -q get snort.nfq.${set_name})
-	if [ -z "$ips" ]; then
-		: > $set_file
+download_rules () {
+	oinkcode="$(uci -q get snort.snort.oinkcode)"
+	if [ -n "$oinkcode" ]; then
+		rm -f /var/ns-snort/*community-rules.tar.gz
+		rules="$(find /var/ns-snort -type f -name "snortrules-*.tar.gz")"
+		[ -n "$rules" ] && return
 	else
-		echo -n "elements = {" > $set_file
-		for ip in $ips; do
-			echo -n " $ip," >> $set_file
-		done
-		echo " }" >> $set_file
-    fi
-}
-
-download_rules_if_needed () {
-	if ! find /var/ns-snort/rules/ -type f -name "*.rules" | grep -q . ; then
-		# no rules file found, start downloaded loop
-		attempt=0
-		until /usr/bin/ns-snort-rules --download; do
-			attempt=$((attempt + 1))
-			if [ "$attempt" -ge 6 ]; then
-				echo "Error: failed to download snort rules after 6 attempts (1 minute)."
-				break
-			fi
-			sleep 10
-		done
+		rm -f /var/ns-snort/snortrules-*.tar.gz
+		rules="$(find /var/ns-snort/ -type f -name "*community-rules.tar.gz")"
+		[ -n "$rules" ] && return
 	fi
+	# this is done every time the service is started
+	attempt=0
+	until /usr/bin/ns-snort-rules --download; do
+		attempt=$((attempt + 1))
+		if [ "$attempt" -ge 6 ]; then
+			echo "Error: failed to download snort rules after 6 attempts (1 minute)."
+			break
+		fi
+		sleep 10
+	done
 }
 
 setup_tweaks() {
@@ -68,7 +61,7 @@ start_service() {
 	# output.logdir, in the snort lua config, determines the PID file location.
 	# Add '--create-pidfile' to the 'command', below.
 
-        local enabled
+	local enabled
 	local manual
 	local config_dir
 	local interface
@@ -78,25 +71,22 @@ start_service() {
 		cdir="$(uci -q get snort.snort.config_dir)"
 		mkdir -p "${cdir}/rules"
 		find /etc/snort -type f ! -name snort.rules -exec cp '{}' "${cdir}" \;
-		update_bypass_set "bypass_src_v4"
-		update_bypass_set "bypass_dst_v4"
-		update_bypass_set "bypass_src_v6"
-		update_bypass_set "bypass_dst_v6"
-		download_rules_if_needed
+		/usr/bin/ns-bypass-config
+		download_rules
 		setup_tweaks
 	fi
 
-        validate_snort_section snort || {
-                echo "Validation failed, try 'snort-mgr check'."
-                return 1
-        }
+	validate_snort_section snort || {
+		echo "Validation failed, try 'snort-mgr check'."
+		return 1
+	}
 
 	[ "$enabled" = 0 ] && return
 
 	procd_open_instance
 	if [ "$manual" = 0 ]; then
 		local config_file=$($MGR setup)
-	        maxlen=$(uci -q get snort.nfq.queue_maxlen)
+		maxlen=$(uci -q get snort.nfq.queue_maxlen)
 		if [ -z "${maxlen}" ]; then
 			maxlen=1024
 		fi
@@ -122,4 +112,10 @@ service_triggers()
 {
 	procd_add_reload_trigger "snort"
 	procd_add_validation validate_snort_section
+}
+
+reload_service()
+{
+	stop
+	start
 }
