builder: read OpenWrt release from tag
Tag example:
- 23.05.2-ns.1.0.0 (stable)
- 23.05.2-ns.0.0.1-alpha1 (unstable)

diff --git a/builder/build-builder b/builder/build-builder
--- a/builder/build-builder
+++ b/builder/build-builder
@@ -7,7 +7,17 @@
 
 set -e
 
-OWRT_VERSION="23.05.2"
+if [[ -n "${CI}" ]]; then
+    # Fetch all history when running con Github CI
+    git fetch --prune --unshallow
+fi
+
+OWRT_VERSION=$(git describe | cut -d'-' -f1)
+
+if [ -z "$OWRT_VERSION" ]; then
+    echo "Missing OWRT_VERSION"
+    exit 1
+fi
 repobase="ghcr.io/nethserver"
 reponame="nethsecurity-builder"
 
