ns-threat_shield: replace ts-ip with banip

diff --git a/packages/ns-threat_shield/files/ts-ip b/packages/ns-threat_shield/files/ts-ip
--- a/packages/ns-threat_shield/files/ts-ip
+++ b/packages/ns-threat_shield/files/ts-ip
@@ -6,19 +6,21 @@
 #
 
 #
-# Threat shield: download lists and setup firewalls
+# Threat shield: download remote blocklist
 #
 
-# Cleanup existing table 
-if nft list tables inet | grep -q 'table inet threat_shield'; then
-    nft delete table inet threat_shield
-fi
+function exit_error {
+    >&2 echo "[ERROR] $@"
+    exit 1
+}
 
-status=$(uci get threat_shield.config.status)
-if [ "$status" == "0" ]; then
-    exit 0
-fi
+SYSTEM_SECRET=$(uci -q get ns-plug.config.secret)
+SYSTEM_ID=$(uci -q get ns-plug.config.system_id)
 
-if /usr/sbin/ts-ip-download; then
-    /usr/sbin/ts-ip-nft | nft -f -
+sources=/etc/banip/banip.nethesis.feeds
+
+if [ ! -z "$SYSTEM_SECRET" ] && [ ! -z "$SYSTEM_ID" ]; then
+    cat $sources | sed -e "s/__USER__/$SYSTEM_ID/" -e "s/__PASSWORD__/$SYSTEM_SECRET/" > /etc/banip/banip.custom.feeds
+else
+    > /etc/banip/banip.custom.feeds
 fi
